### ISSUE TITLE
Needs fix: Server Crashed on Script

### ISSUE THREAD

**Issue by fishies** [OdysseyClassicHistoryBook/odyssey-realms-server#16]
**Reproduce:** 
1. ```/god editscript COMMAND``` (or any other script: MAP#_X_Y will crash as well)
2. Save the script without adding any other code.
3. Attempt to run the script (type a command for COMMAND, walk on the script-tile for MAP#_X_Y, etc.)

@QBcrusher thinks it may have something to do with `End Function` (I believe subroutines also crash though).

**Comment by jrdnmldr** [comment]
This error is caused due to script.dll missing. If you place it in the ody-bin folder, it should fix the issue. I also had to add VB.bin 

IIRC, I found these two files in other odyssey projects.

**Comment by QBcrusher** [comment]
@jrdnmldr I already have script.dll in the server folder...any idea where I can find VB.bin? If it's in another Odyssey project, I'm sure I have it on the website, just having trouble finding it.

**Comment by jrdnmldr** [comment]
I was just about to edit. Copy the files from the server folder into the client folder.

**Comment by QBcrusher** [comment]
Alright will do, thanks
