### ISSUE TITLE
Max Characters for Items and Monsters too Short

### ISSUE THREAD

**Issue by QBcrusher** [OdysseyClassicHistoryBook/odyssey-realms-server#17]
An issue a lot of server admins have dealt with in the past is not having enough characters to use for items and monster names. It seems that currently, the max is 15. This doesn't really leave enough room for customization, and usually leads to tacky shortened names or abbreviations being used. 

Example; Hammer of Frost uses the max amount of characters, if one wanted to make a repairable version and define that in the name, something like Hammer of Frost (R) would be too long, they'd have to shorten it to something like HoF (R). 

It would be great if we could somehow increase that value. I'm not sure if this is possible with the current VB6 version, but I figure it's worth adding an issue for,

**Comment by jrdnmldr** [comment]
I changed...
Item/Monster/NPC names to 35 characters
Guild/Magic names to 25 characters
Prefix/Suffix names to 20 characters

I can't commit changes so I zipped up the files I changed. At least I think it was all of them :-D

These changes also include the changes to the flags. I changed player flags to 5,000 and server flags to 1024. Here I would like to note using the ini functions when scripting, you can essentially set an unlimited number of flags easily.

I tested all the new code and think I worked out all the kinks.

[changes.zip](https://github.com/OdysseyClassicHistoryBook/odyssey-realms-server/files/1347571/changes.zip)

**Comment by QBcrusher** [comment]
Very nice, thank you. How come you can't commit? The contributors team should have permissions to do that.

**Comment by jrdnmldr** [comment]
Its possible I'm doing something wrong, I've never done anything like this before; When I try to upload files, it says the branch is protected and that I need to make a new branch and start a pull request.

-Edit-
So it seems I was just being lazy when I decided I couldn't commit changes. I found a guide on how to do it and am setting up right now. Local time is getting late (or early depending on ones point of view) so I may get to committing the changes tonight, but possibly tomorrow. I assume everyone gets a notice so if you could let me know if I did it right, that would be helpful.
